export const ENDPOINTS = {
  auth: {
    superAdminLogin: "/auth/superadmin/login",
    adminLogin: "/auth/admin/login",
    departmentManagerLogin: "/auth/department-manager/login",
    studentLogin: "/auth/student/login",
    studentRegister: "/auth/student/register",
  },
  students: {
    list: "/students",
    create: "/students",
    bulk: "/students/bulk",
    get: (id: string) => `/students/${id}`,
    update: (id: string) => `/students/${id}`,
    delete: (id: string) => `/students/${id}`,
    updateAboutMe: (id: string) => `/students/${id}/about-me`,
  },
  attendance: {
    mark: "/attendance/mark",
    selfMark: "/attendance/self-mark",
    markById: (studentId: string) => `/attendance/${studentId}/mark`,
    update: (studentId: string) => `/attendance/${studentId}`,
    studentAttendance: (studentId: string) => `/attendance/student/${studentId}`,
    report: "/attendance/report",
  },
  departmentManagers: {
    list: "/department-managers",
    create: "/department-managers",
    get: (id: string) => `/department-managers/${id}`,
    update: (id: string) => `/department-managers/${id}`,
    delete: (id: string) => `/department-managers/${id}`,
  },
  admins: {
    list: "/admins",
    create: "/admins",
    get: (id: string) => `/admins/${id}`,
    update: (id: string) => `/admins/${id}`,
    delete: (id: string) => `/admins/${id}`,
  },
  messages: {
    list: "/messages",
    create: "/messages",
    updateStatus: (id: string) => `/messages/${id}`,
  },
  userLogs: {
    list: "/user-logs",
    update: (id: string) => `/user-logs/${id}`,
    delete: (id: string) => `/user-logs/${id}`,
  },
};